from enum import Enum

class DatasetType(Enum):
    LANDSAT8_OLI_TIRS_C1_LEVEL1 = 'LC8'
    LANDSAT7_ETM_C1_LEVEL1 = 'LE7'
    LANDSAT5_TM_C1_LEVEL1 = 'LT5'

class METADATA_FILE_INFO(Enum):
    ORIGIN = 'ORIGIN'
    REQUEST_ID = 'REQUEST_ID'
    LANDSAT_SCENE_ID = 'LANDSAT_SCENE_ID'
    LANDSAT_PRODUCT_ID = 'LANDSAT_PRODUCT_ID'
    FILE_DATE = 'FILE_DATE'
    STATION_ID = 'STATION_ID'


class ImageAttribute(Enum):
    CLOUDCOVER = 'CLOUDCOVER'
    CLOUDCOVER_LAND = 'CLOUDCOVER_LAND'
    IMAGE_QUALITY_OLI = 'IMAGE_QUALITY_OLI'
    IMAGE_QUALITY_TIRS = 'IMAGE_QUALITY_TIRS'


class PRODUCT_METADATA(Enum):
    NADIR_OFFNADIR = 'NADIR_OFFNADIR'
    DATE_ACQUIRED = 'DATE_ACQUIRED'
